//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Procedures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Procedures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HospitalManagementSystem.Resources.Procedures", typeof(Procedures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientInformationDetailsGetByAll.
        /// </summary>
        internal static string PatientInformationDetailsGetByAll {
            get {
                return ResourceManager.GetString("PatientInformationDetailsGetByAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientInformationDetailsGetBySearch.
        /// </summary>
        internal static string PatientInformationDetailsGetBySearch {
            get {
                return ResourceManager.GetString("PatientInformationDetailsGetBySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientInformationDetailsGetBySearchForTreatment.
        /// </summary>
        internal static string PatientInformationDetailsGetBySearchForTreatment {
            get {
                return ResourceManager.GetString("PatientInformationDetailsGetBySearchForTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientMasterDetailsInsertUpdateDelete.
        /// </summary>
        internal static string PatientMasterDetailsInsertUpdateDelete {
            get {
                return ResourceManager.GetString("PatientMasterDetailsInsertUpdateDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreatmentInformationDetailsByAll.
        /// </summary>
        internal static string TreatmentInformationDetailsByAll {
            get {
                return ResourceManager.GetString("TreatmentInformationDetailsByAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreatmentInformationDetailsInsertUpdateDelete.
        /// </summary>
        internal static string TreatmentInformationDetailsInsertUpdateDelete {
            get {
                return ResourceManager.GetString("TreatmentInformationDetailsInsertUpdateDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationDetailsGetByAll.
        /// </summary>
        internal static string UserInformationDetailsGetByAll {
            get {
                return ResourceManager.GetString("UserInformationDetailsGetByAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationDetailsInsertUpdateDelete.
        /// </summary>
        internal static string UserInformationDetailsInsertUpdateDelete {
            get {
                return ResourceManager.GetString("UserInformationDetailsInsertUpdateDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidUserLoginCheck_USP.
        /// </summary>
        internal static string ValidUserLoginCheck_USP {
            get {
                return ResourceManager.GetString("ValidUserLoginCheck_USP", resourceCulture);
            }
        }
    }
}
